// <auto-generated />
namespace LearnerProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class coursevideo_add_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(coursevideo_add_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202405011015268_coursevideo_add_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
